# Mid EXAM : Tools and Techniques Data Science 

# Task 1: ( 5 Marks)  Warp up 

# Note : Rename the file with your name and id and also mention your name and id inside here 

In [45]:
# Q1. Here, we take each element in the list a (temporarily assigning it the value i) 
a = [5, 10, 15, 20]

In [46]:
# (i)	Find the square each element in the list. This creates a new list called b and does not modify a through data comprehension.

In [47]:
b = list(map(lambda x: x**2,a))
print(b)

[25, 100, 225, 400]


In [88]:
# (ii)	Write a conditional statement of only squaring the elements if the element is not equal to 10.
b = list(map(lambda x: x**2 if x != 10 else x,a))
print(b)

[25, 10, 225, 400]


In [49]:
# Q2. (i) Write the command of random samples from a uniform distribution between 0 and 1? 

In [50]:
import numpy as np 
import random

In [51]:
x = np.random.uniform(0, 1, size=(5,5))
print(x)

[[0.72327105 0.44385907 0.46684722 0.27884162 0.15643467]
 [0.3127829  0.27729335 0.77273845 0.75434162 0.48797324]
 [0.02459943 0.51709556 0.54853596 0.12777197 0.48421353]
 [0.74580275 0.97617643 0.23057971 0.34050239 0.28460762]
 [0.23241554 0.50640776 0.48196714 0.17051866 0.53817366]]


In [52]:
y = slice(1)
y = x[y]
print(y)

[[0.72327105 0.44385907 0.46684722 0.27884162 0.15643467]]


In [53]:
#(iii)	Write the command of first and third elements in column 1?

In [54]:
first_element = y[0][0]
third_element = y[0][2]
print(first_element,third_element)

0.7232710518281449 0.46684721821228703


In [55]:
#(iv)	 Write the command of returns an 8 x 4 array

In [56]:
array8x4 = np.random.uniform(0, 1, size=(8,4))
print(array8x4)

[[0.22782915 0.61357063 0.37344981 0.61965058]
 [0.19952603 0.06507939 0.77216789 0.13918042]
 [0.22277702 0.58910058 0.57150476 0.17872173]
 [0.62899839 0.89921043 0.03605846 0.55300667]
 [0.05897571 0.91846012 0.64339232 0.34830607]
 [0.28641196 0.11316289 0.39408307 0.11831226]
 [0.59936787 0.06550817 0.58103593 0.70707115]
 [0.55364066 0.33951483 0.82876309 0.84384091]]


In [57]:
import pandas as pd 

In [58]:
#Q3. Create a Series that looks like this below:
# Flour     4 cups
# Milk       1 cup
# Eggs     2 large
# Spam       1 can
# Name: Dinner, dtype: object

In [59]:
index = ["Flour", "Milk", "Eggs", "Spam"]
element = ["4 cups", "1 cup", "2 large", "1 can"]
pd.Series(element, index = index , name="Dinner")


Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object

In [60]:
# Q  4 Create the Data frame  as th output[27]

In [67]:
data = {"Apples" : [35,41], "Bananas" : [21,34]}
index = ["2017Sales", "2018Sales"]
df = pd.DataFrame(data, index)
print(df)

           Apples  Bananas
2017Sales      35       21
2018Sales      41       34


In [68]:
df

Apples  Bananas
2017Sales      35       21
2018Sales      41       34

In [63]:
#Q4. create Dataframe then find imputation for these missing NaN in the out[47]

In [70]:
data = {
    "Age" : [23.0, 39.0, 45.0, np.NaN],
    "Gender" : ["M", "F", "F", "M"],
    "Income" : [24200.0, np.NaN, 45390.0, np.NaN],
    "Religion" : ["Muslim", "chirstian", np.NaN, "Muslim"]
}
index = [0,1,2,3]
df = pd.DataFrame(data, index)
print(df)

    Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F      NaN  chirstian
2  45.0      F  45390.0        NaN
3   NaN      M      NaN     Muslim


In [71]:
df

Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F      NaN  chirstian
2  45.0      F  45390.0        NaN
3   NaN      M      NaN     Muslim

In [39]:
#Q4(i)	Compute the appropriate missing value in income attribute?

In [96]:
df["Income"].mean()

34795.0

In [49]:
#(ii)	Compute the appropriate missing values in religion attribute? 

In [101]:
df["Religion"].mode()[0]

'Muslim'

In [53]:
#(iii)	Drop the columns where any of the elements is nan

In [81]:
dropped = df.dropna(axis=1)
print(dropped)

  Gender
0      M
1      F
2      F
3      M


In [55]:
#(iv)	Keep only the rows with at least 2 non-na values

In [95]:
dropped = df.dropna(thresh=2)
print(dropped)

    Age Gender   Income   Religion
0  23.0      M  24200.0     Muslim
1  39.0      F      NaN  chirstian
2  45.0      F  45390.0        NaN
3   NaN      M      NaN     Muslim
